services:


  # ======================
  # Laravel API (PHP)
  # ======================
  api:
    build:
      context: ./docker/api
    container_name: laravel_api
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000


  # ======================
  # Nuxt Frontend
  # ======================
  frontend:
    image: node:20
    container_name: nuxt_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


  # ======================
  # MySQL
  # ======================
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql


  # ======================
  # PhpMyAdmin (debug)
  # ======================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root


volumes:
  dbdata:
